import { PrismaClient, SkillCategory } from "@prisma/client";

const prisma = new PrismaClient();

export interface SeedCareerRole {
  title: string;
  domain: string;
  description: string;
  courses: string[];
  departments: string[];
  isCrossDisciplinary: boolean;
  experienceLevel: string;
  educationRequirements: string;
  salaryRange: string;
  certifications: string[];
  toolsAndTechnologies: string[];
  skills: {
    skillName: string;
    category?: SkillCategory;
    requiredLevel: number;
    weight: number;
    priority: number;
  }[];
}

export const CAREER_ROLES_SEED: SeedCareerRole[] = [
  // ═════════════════════════════════════════════════════════════════════════
  // 1. COMPUTER SCIENCE & IT ROLES (B.Tech CSE, IT, BCA, B.Sc CS, MCA)
  // ═════════════════════════════════════════════════════════════════════════
  {
    title: "Software Engineer",
    domain: "Software Engineering",
    description: "Design, build, and maintain robust production software applications and core algorithms.",
    courses: ["B.Tech", "BE", "BCA", "MCA", "B.Sc", "M.Tech"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Software Engineering", "Computer Applications"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/BE in CS/IT or BCA/MCA",
    salaryRange: "₹6,00,000 - ₹18,00,000 / year",
    certifications: ["Oracle Certified Associate Java", "AWS Certified Developer", "Meta Software Engineer Certificate"],
    toolsAndTechnologies: ["Git", "Docker", "VS Code", "Postman", "Linux", "JUnit/PyTest"],
    skills: [
      { skillName: "Data Structures", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 2 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "Git", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 0.7, priority: 4 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 5 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 70, weight: 0.6, priority: 6 },
    ],
  },
  {
    title: "Software Developer",
    domain: "Application Development",
    description: "Develop enterprise backend logic, APIs, and end-user software products across platforms.",
    courses: ["B.Tech", "BE", "BCA", "MCA", "B.Sc"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Computer Applications"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/BE/BCA/B.Sc Computer Science",
    salaryRange: "₹5,50,000 - ₹15,00,000 / year",
    certifications: ["Oracle Java SE Certified", "Microsoft Certified: Azure Developer Associate"],
    toolsAndTechnologies: ["Java", "Python", "Git", "MySQL", "REST APIs"],
    skills: [
      { skillName: "Data Structures", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.2, priority: 1 },
      { skillName: "Java", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.1, priority: 2 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.9, priority: 4 },
      { skillName: "Git", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.6, priority: 5 },
    ],
  },
  {
    title: "Full Stack Developer",
    domain: "Web & Enterprise Development",
    description: "Develop end-to-end web applications combining dynamic frontends, scalable backend services, and databases.",
    courses: ["B.Tech", "BE", "BCA", "MCA", "B.Sc", "M.Tech"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Computer Applications"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/BE/BCA/B.Sc Computer Science or equivalent",
    salaryRange: "₹6,50,000 - ₹16,00,000 / year",
    certifications: ["Meta Front-End & Back-End Professional Certificate", "AWS Certified Developer - Associate"],
    toolsAndTechnologies: ["React", "Next.js", "Node.js", "Express", "PostgreSQL", "Tailwind CSS", "Git"],
    skills: [
      { skillName: "JavaScript", category: SkillCategory.TECHNICAL, requiredLevel: 85, weight: 1.2, priority: 1 },
      { skillName: "React", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.1, priority: 2 },
      { skillName: "Node.js", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.8, priority: 4 },
      { skillName: "Git", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 0.6, priority: 5 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.8, priority: 6 },
    ],
  },
  {
    title: "Frontend Developer",
    domain: "Web & UI Engineering",
    description: "Craft modern, accessible, and high-performance interactive user interfaces and responsive web applications.",
    courses: ["B.Tech", "BCA", "B.Sc", "MCA"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Computer Applications"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Degree in Computer Science, Design, or equivalent portfolio",
    salaryRange: "₹5,50,000 - ₹14,00,000 / year",
    certifications: ["Meta Front-End Developer Certificate", "freeCodeCamp Responsive Web Design"],
    toolsAndTechnologies: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Figma", "Redux Toolkit"],
    skills: [
      { skillName: "JavaScript", category: SkillCategory.TECHNICAL, requiredLevel: 85, weight: 1.2, priority: 1 },
      { skillName: "React", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "TypeScript", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Git", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.6, priority: 4 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 70, weight: 0.5, priority: 5 },
    ],
  },
  {
    title: "Backend Developer",
    domain: "Backend & Systems",
    description: "Architect high-throughput server-side APIs, database systems, caching layers, and microservices.",
    courses: ["B.Tech", "BE", "BCA", "MCA", "B.Sc"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Computer Applications"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/BE in CS/IT or MCA/BCA",
    salaryRange: "₹6,00,000 - ₹17,00,000 / year",
    certifications: ["AWS Certified Developer Associate", "Oracle Certified Professional Java"],
    toolsAndTechnologies: ["Node.js", "Express", "Docker", "PostgreSQL", "Redis", "Kafka", "Postman"],
    skills: [
      { skillName: "Node.js", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Docker", category: SkillCategory.TECHNICAL, requiredLevel: 65, weight: 0.8, priority: 4 },
      { skillName: "Data Structures", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 0.9, priority: 5 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.8, priority: 6 },
    ],
  },
  {
    title: "Web Developer",
    domain: "Web Development",
    description: "Build clean, standards-compliant websites, landing pages, and content management web systems.",
    courses: ["B.Tech", "BCA", "B.Sc", "MCA"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Computer Applications"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "BCA, B.Sc CS, or B.Tech",
    salaryRange: "₹4,50,000 - ₹11,00,000 / year",
    certifications: ["W3C Web Developer Certification", "Meta Frontend Certificate"],
    toolsAndTechnologies: ["HTML/CSS", "JavaScript", "React", "WordPress", "Git"],
    skills: [
      { skillName: "JavaScript", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "React", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.1, priority: 2 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 65, weight: 0.8, priority: 3 },
      { skillName: "Git", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.6, priority: 4 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 70, weight: 0.6, priority: 5 },
    ],
  },
  {
    title: "Mobile App Developer",
    domain: "Mobile Engineering",
    description: "Develop native and cross-platform mobile apps for iOS and Android with intuitive user interactions.",
    courses: ["B.Tech", "BCA", "MCA", "B.Sc"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Computer Applications"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Degree in Computer Science or Software Engineering",
    salaryRange: "₹6,00,000 - ₹16,00,000 / year",
    certifications: ["Google Associate Android Developer", "Meta React Native Specialization"],
    toolsAndTechnologies: ["React Native", "Flutter", "TypeScript", "Android Studio", "Xcode"],
    skills: [
      { skillName: "JavaScript", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "React", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "Data Structures", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "Git", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 0.7, priority: 4 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.8, priority: 5 },
    ],
  },
  {
    title: "Cloud Engineer",
    domain: "Cloud & Infrastructure",
    description: "Design, provision, and maintain resilient enterprise cloud architectures, serverless workloads, and storage systems.",
    courses: ["B.Tech", "BE", "BCA", "MCA", "B.Sc"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Cloud Computing"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/BE in Computer Science, IT, or Electronics",
    salaryRange: "₹7,00,000 - ₹18,00,000 / year",
    certifications: ["AWS Certified Solutions Architect - Associate", "Microsoft Certified: Azure Fundamentals"],
    toolsAndTechnologies: ["AWS", "Terraform", "Docker", "Kubernetes", "Linux", "Bash"],
    skills: [
      { skillName: "AWS", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "Docker", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 2 },
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 65, weight: 0.7, priority: 4 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.8, priority: 5 },
    ],
  },
  {
    title: "DevOps Engineer",
    domain: "DevOps & Infrastructure",
    description: "Automate build, test, and deployment pipelines (CI/CD), infrastructure as code, and container orchestration.",
    courses: ["B.Tech", "BE", "MCA", "B.Sc"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/BE in CS/IT or MCA",
    salaryRange: "₹7,50,000 - ₹19,00,000 / year",
    certifications: ["Certified Kubernetes Administrator (CKA)", "AWS Certified DevOps Engineer"],
    toolsAndTechnologies: ["Docker", "Kubernetes", "GitHub Actions", "Terraform", "Jenkins", "Prometheus"],
    skills: [
      { skillName: "Docker", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "Git", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.0, priority: 2 },
      { skillName: "AWS", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.8, priority: 4 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.8, priority: 5 },
    ],
  },
  {
    title: "Database Administrator",
    domain: "Database Architecture",
    description: "Manage database security, indexing, backup recovery, clustering, and SQL performance tuning.",
    courses: ["B.Tech", "BCA", "MCA", "B.Sc"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Computer Applications"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech in CS/IT, BCA, or MCA",
    salaryRange: "₹6,00,000 - ₹15,00,000 / year",
    certifications: ["Oracle Database Administrator Certified Associate", "PostgreSQL Certified Associate"],
    toolsAndTechnologies: ["PostgreSQL", "MySQL", "MongoDB", "pgAdmin", "Docker", "Linux"],
    skills: [
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 85, weight: 1.3, priority: 1 },
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.8, priority: 2 },
      { skillName: "Data Structures", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.8, priority: 3 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.9, priority: 4 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.8, priority: 5 },
    ],
  },
  {
    title: "QA / Test Engineer",
    domain: "Quality Assurance & Testing",
    description: "Design automated test suites, execute regression checks, and ensure flawless software reliability.",
    courses: ["B.Tech", "BCA", "MCA", "B.Sc"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Computer Applications"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Degree in Computer Science, IT, or Applications",
    salaryRange: "₹4,50,000 - ₹12,00,000 / year",
    certifications: ["ISTQB Certified Tester", "Selenium Automation Certificate"],
    toolsAndTechnologies: ["Selenium", "Postman", "Cypress", "Jira", "PyTest", "Git"],
    skills: [
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.1, priority: 1 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 2 },
      { skillName: "JavaScript", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 1.0, priority: 4 },
      { skillName: "Git", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.6, priority: 5 },
    ],
  },

  // ═════════════════════════════════════════════════════════════════════════
  // 2. ARTIFICIAL INTELLIGENCE & MACHINE LEARNING ROLES
  // ═════════════════════════════════════════════════════════════════════════
  {
    title: "Machine Learning Engineer",
    domain: "AI & Intelligent Systems",
    description: "Design, train, optimize, and deploy predictive machine learning models and feature engineering pipelines in production.",
    courses: ["B.Tech", "BE", "M.Tech", "B.Sc", "MCA"],
    departments: ["Artificial Intelligence & Machine Learning", "Computer Science & Engineering", "Computer Science", "Data Science & Analytics", "Information Technology"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/M.Tech in AI/ML, CS, Data Science, or Mathematics",
    salaryRange: "₹8,00,000 - ₹22,00,000 / year",
    certifications: ["TensorFlow Developer Certificate", "AWS Certified Machine Learning - Specialty", "DeepLearning.AI ML Specialization"],
    toolsAndTechnologies: ["Python", "Scikit-Learn", "PyTorch", "TensorFlow", "Pandas", "Docker", "MLflow"],
    skills: [
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 85, weight: 1.2, priority: 1 },
      { skillName: "Machine Learning", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "Deep Learning", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 1.0, priority: 3 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.8, priority: 4 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 0.9, priority: 5 },
      { skillName: "Quantitative Aptitude", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.8, priority: 6 },
    ],
  },
  {
    title: "AI Engineer",
    domain: "Artificial Intelligence",
    description: "Develop agentic AI systems, LLM-powered applications, computer vision, and cognitive automation pipelines.",
    courses: ["B.Tech", "BE", "M.Tech", "MCA"],
    departments: ["Artificial Intelligence & Machine Learning", "Computer Science & Engineering", "Computer Science", "Data Science & Analytics"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/M.Tech in AI/CS or computational degree",
    salaryRange: "₹8,50,000 - ₹24,00,000 / year",
    certifications: ["DeepLearning.AI Generative AI Specialization", "NVIDIA Deep Learning Institute Certificate"],
    toolsAndTechnologies: ["PyTorch", "LangChain", "Hugging Face", "OpenAI API", "Vector Databases", "Docker"],
    skills: [
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 85, weight: 1.2, priority: 1 },
      { skillName: "Deep Learning", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "Machine Learning", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.7, priority: 4 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 5 },
    ],
  },
  {
    title: "Deep Learning Engineer",
    domain: "Neural Networks & Deep Learning",
    description: "Design multi-layer neural networks, CNNs, RNNs, and custom loss architectures for complex perception tasks.",
    courses: ["B.Tech", "M.Tech", "B.Sc"],
    departments: ["Artificial Intelligence & Machine Learning", "Data Science & Analytics", "Computer Science & Engineering", "Computer Science"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/M.Tech in AI, CS, or Data Science",
    salaryRange: "₹9,00,000 - ₹25,00,000 / year",
    certifications: ["DeepLearning.AI Deep Learning Specialization", "NVIDIA DLI Certificate"],
    toolsAndTechnologies: ["PyTorch", "TensorFlow", "CUDA", "Pandas", "OpenCV", "Docker"],
    skills: [
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 85, weight: 1.2, priority: 1 },
      { skillName: "Deep Learning", category: SkillCategory.TECHNICAL, requiredLevel: 85, weight: 1.3, priority: 2 },
      { skillName: "Machine Learning", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 4 },
      { skillName: "Quantitative Aptitude", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 5 },
    ],
  },
  {
    title: "MLOps Engineer",
    domain: "ML Engineering & Operations",
    description: "Automate machine learning model lifecycle, training pipelines, model registry, monitoring, and scalable deployment.",
    courses: ["B.Tech", "M.Tech", "MCA"],
    departments: ["Artificial Intelligence & Machine Learning", "Computer Science & Engineering", "Computer Science", "Information Technology"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech in AI/ML, CS, or IT",
    salaryRange: "₹8,00,000 - ₹22,00,000 / year",
    certifications: ["AWS Certified Machine Learning Specialty", "DeepLearning.AI MLOps Specialization"],
    toolsAndTechnologies: ["Docker", "Kubernetes", "MLflow", "Kubeflow", "Python", "AWS", "Git"],
    skills: [
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "Machine Learning", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 2 },
      { skillName: "Docker", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 3 },
      { skillName: "AWS", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 4 },
      { skillName: "Git", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 0.8, priority: 5 },
    ],
  },
  {
    title: "Generative AI Engineer",
    domain: "Large Language Models & GenAI",
    description: "Build LLM applications, RAG pipelines, prompt systems, fine-tuning workflows, and multimodal agents.",
    courses: ["B.Tech", "M.Tech", "MCA"],
    departments: ["Artificial Intelligence & Machine Learning", "Computer Science & Engineering", "Computer Science", "Data Science & Analytics"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Degree in AI, Computer Science, or computational field",
    salaryRange: "₹9,50,000 - ₹26,00,000 / year",
    certifications: ["DeepLearning.AI LangChain / Generative AI Specialization", "Anthropic / OpenAI API Badges"],
    toolsAndTechnologies: ["LangChain", "LlamaIndex", "ChromaDB/Pinecone", "Hugging Face", "Python", "Docker"],
    skills: [
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 85, weight: 1.2, priority: 1 },
      { skillName: "Deep Learning", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "Machine Learning", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 4 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 75, weight: 0.7, priority: 5 },
    ],
  },

  // ═════════════════════════════════════════════════════════════════════════
  // 3. COMMERCE, FINANCE & ACCOUNTING ROLES (B.Com, M.Com, BBA Finance)
  // ═════════════════════════════════════════════════════════════════════════
  {
    title: "Financial Analyst",
    domain: "Corporate Finance & Capital Markets",
    description: "Conduct financial modeling, DCF valuation, variance analysis, and capital allocation forecasting for corporate growth.",
    courses: ["B.Com", "M.Com", "BBA", "MBA"],
    departments: ["Accounting & Finance", "Banking & Insurance", "Financial Markets", "Finance & Investment Banking", "General Commerce", "Finance"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Com / BBA in Finance, M.Com, or MBA Finance",
    salaryRange: "₹6,00,000 - ₹16,00,000 / year",
    certifications: ["CFA Level 1 Passed", "Financial Modeling & Valuation Analyst (FMVA)", "NCFM Certifications"],
    toolsAndTechnologies: ["MS Excel (Advanced)", "Power BI", "Bloomberg Terminal", "TallyPrime", "ERP"],
    skills: [
      { skillName: "Financial Analysis", category: SkillCategory.DOMAIN, requiredLevel: 85, weight: 1.3, priority: 1 },
      { skillName: "Financial Management", category: SkillCategory.DOMAIN, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "Accounting", category: SkillCategory.DOMAIN, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Economics", category: SkillCategory.DOMAIN, requiredLevel: 70, weight: 0.8, priority: 4 },
      { skillName: "Quantitative Aptitude", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 5 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 75, weight: 0.7, priority: 6 },
    ],
  },
  {
    title: "Accountant",
    domain: "Financial Accounting & Auditing",
    description: "Manage general ledger entries, reconcile accounts, prepare balance sheets, and ensure statutory regulatory compliance.",
    courses: ["B.Com", "M.Com", "BBA"],
    departments: ["Accounting & Finance", "Taxation", "General Commerce", "Corporate Secretaryship"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Com in Accounting/Finance or M.Com",
    salaryRange: "₹4,00,000 - ₹10,00,000 / year",
    certifications: ["Tally Certified Professional", "Certified Management Accountant (CMA) Foundation"],
    toolsAndTechnologies: ["TallyPrime", "QuickBooks", "SAP FICO", "MS Excel", "GST Portal"],
    skills: [
      { skillName: "Accounting", category: SkillCategory.DOMAIN, requiredLevel: 85, weight: 1.4, priority: 1 },
      { skillName: "Taxation", category: SkillCategory.DOMAIN, requiredLevel: 75, weight: 1.1, priority: 2 },
      { skillName: "Financial Management", category: SkillCategory.DOMAIN, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "Quantitative Aptitude", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.9, priority: 4 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 70, weight: 0.6, priority: 5 },
    ],
  },
  {
    title: "Tax Consultant",
    domain: "Taxation & Regulatory Law",
    description: "Advise corporate and individual clients on direct tax planning, GST filing compliance, and tax litigation defense.",
    courses: ["B.Com", "M.Com", "LLB / BA LLB"],
    departments: ["Taxation", "Accounting & Finance", "Corporate & Commercial Law", "General Commerce"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Com Taxation, CA Inter, or Law Degree",
    salaryRange: "₹5,00,000 - ₹14,00,000 / year",
    certifications: ["GST Practitioner Certificate", "Income Tax Specialist Certification"],
    toolsAndTechnologies: ["Income Tax e-Filing Portal", "GST Portal", "ClearTax", "Excel"],
    skills: [
      { skillName: "Taxation", category: SkillCategory.DOMAIN, requiredLevel: 85, weight: 1.4, priority: 1 },
      { skillName: "Accounting", category: SkillCategory.DOMAIN, requiredLevel: 80, weight: 1.1, priority: 2 },
      { skillName: "Financial Analysis", category: SkillCategory.DOMAIN, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.9, priority: 4 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 75, weight: 0.8, priority: 5 },
    ],
  },
  {
    title: "Audit Associate",
    domain: "Auditing & Internal Controls",
    description: "Perform statutory audits, verify voucher documentation, check internal financial controls, and prepare audit reports.",
    courses: ["B.Com", "M.Com"],
    departments: ["Accounting & Finance", "Auditing", "Corporate Secretaryship", "General Commerce"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Com in Accounting/Auditing or CA Inter",
    salaryRange: "₹4,50,000 - ₹12,00,000 / year",
    certifications: ["Certified Internal Auditor (CIA) Candidate", "TallyPrime Audit Certificate"],
    toolsAndTechnologies: ["MS Excel", "TallyPrime", "Audit Automation Software", "SAP"],
    skills: [
      { skillName: "Accounting", category: SkillCategory.DOMAIN, requiredLevel: 85, weight: 1.3, priority: 1 },
      { skillName: "Financial Analysis", category: SkillCategory.DOMAIN, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "Taxation", category: SkillCategory.DOMAIN, requiredLevel: 70, weight: 0.8, priority: 3 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 4 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 75, weight: 0.8, priority: 5 },
    ],
  },
  {
    title: "Investment Analyst",
    domain: "Investment Banking & Equity Research",
    description: "Analyze market equity trends, evaluate investment securities, prepare pitch decks, and build financial models.",
    courses: ["B.Com", "BBA", "M.Com", "MBA"],
    departments: ["Accounting & Finance", "Financial Markets", "Banking & Insurance", "Finance"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Com / BBA Finance or MBA",
    salaryRange: "₹7,00,000 - ₹20,00,000 / year",
    certifications: ["CFA Level 1 Passed", "NCFM Equity Research Module", "FMVA"],
    toolsAndTechnologies: ["Bloomberg", "Excel Modeling", "Capital IQ", "Power BI"],
    skills: [
      { skillName: "Financial Analysis", category: SkillCategory.DOMAIN, requiredLevel: 85, weight: 1.3, priority: 1 },
      { skillName: "Financial Management", category: SkillCategory.DOMAIN, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "Economics", category: SkillCategory.DOMAIN, requiredLevel: 80, weight: 1.0, priority: 3 },
      { skillName: "Quantitative Aptitude", category: SkillCategory.APTITUDE, requiredLevel: 85, weight: 1.1, priority: 4 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 5 },
    ],
  },

  // ═════════════════════════════════════════════════════════════════════════
  // 4. MANAGEMENT & BUSINESS ROLES (BBA, MBA)
  // ═════════════════════════════════════════════════════════════════════════
  {
    title: "Marketing Executive",
    domain: "Marketing & Brand Strategy",
    description: "Design omnichannel customer acquisition campaigns, brand storytelling, market research, and lead generation.",
    courses: ["BBA", "MBA", "B.Com", "BA"],
    departments: ["Marketing", "Digital Marketing", "International Business", "Mass Communication", "General Management"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "BBA/MBA in Marketing, Mass Comm, or Commerce",
    salaryRange: "₹4,50,000 - ₹12,00,000 / year",
    certifications: ["Google Digital Marketing Certificate", "HubSpot Inbound Marketing"],
    toolsAndTechnologies: ["Google Analytics", "HubSpot", "Meta Ads Manager", "Canva", "Mailchimp"],
    skills: [
      { skillName: "Marketing", category: SkillCategory.DOMAIN, requiredLevel: 85, weight: 1.3, priority: 1 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 85, weight: 1.2, priority: 2 },
      { skillName: "Business Analytics", category: SkillCategory.DOMAIN, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "Leadership", category: SkillCategory.SOFT_SKILL, requiredLevel: 75, weight: 0.8, priority: 4 },
      { skillName: "Teamwork", category: SkillCategory.SOFT_SKILL, requiredLevel: 80, weight: 0.8, priority: 5 },
    ],
  },
  {
    title: "Digital Marketing Specialist",
    domain: "Digital Marketing & Performance Media",
    description: "Manage paid search (SEM), SEO organic growth, social media ad funnels, and conversion rate optimization (CRO).",
    courses: ["BBA", "MBA", "B.Com", "BCA"],
    departments: ["Digital Marketing", "Marketing", "Mass Communication", "E-Commerce"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Degree in Business, Marketing, or Media",
    salaryRange: "₹4,50,000 - ₹13,00,000 / year",
    certifications: ["Google Search Ads & Analytics Certified", "Meta Certified Digital Marketing Associate"],
    toolsAndTechnologies: ["Google Ads", "GA4", "SEMrush", "Meta Ads", "WordPress"],
    skills: [
      { skillName: "Marketing", category: SkillCategory.DOMAIN, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 80, weight: 1.1, priority: 2 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Business Analytics", category: SkillCategory.DOMAIN, requiredLevel: 70, weight: 0.8, priority: 4 },
    ],
  },
  {
    title: "HR Executive",
    domain: "Human Resources & Talent Acquisition",
    description: "Manage talent recruitment pipelines, employee onboarding, performance appraisals, and workplace culture.",
    courses: ["BBA", "MBA", "B.Com", "BA"],
    departments: ["Human Resource Management", "General Management", "Organizational Behavior", "Management"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "BBA/MBA in HR or Psychology/Commerce",
    salaryRange: "₹4,00,000 - ₹11,00,000 / year",
    certifications: ["SHRM Certified Professional (SHRM-CP)", "HRCI Associate"],
    toolsAndTechnologies: ["Darwinbox", "LinkedIn Recruiter", "Workday", "MS Excel", "Keka"],
    skills: [
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 85, weight: 1.3, priority: 1 },
      { skillName: "Leadership", category: SkillCategory.SOFT_SKILL, requiredLevel: 80, weight: 1.1, priority: 2 },
      { skillName: "Teamwork", category: SkillCategory.SOFT_SKILL, requiredLevel: 85, weight: 1.1, priority: 3 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.9, priority: 4 },
    ],
  },

  // ═════════════════════════════════════════════════════════════════════════
  // 5. ELECTRONICS, MECHANICAL & CIVIL ENGINEERING ROLES
  // ═════════════════════════════════════════════════════════════════════════
  {
    title: "Embedded Systems Engineer",
    domain: "Embedded & Hardware Engineering",
    description: "Develop firmware, microcontroller drivers, RTOS kernels, and hardware-software communication interfaces.",
    courses: ["B.Tech", "BE", "M.Tech", "Diploma"],
    departments: ["Electronics & Communication Engineering", "Electrical & Electronics Engineering", "Robotics & Automation", "Electronics"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/BE in ECE, EEE, Embedded Systems, or Robotics",
    salaryRange: "₹6,00,000 - ₹16,00,000 / year",
    certifications: ["ARM Accredited Engineer", "Embedded Linux Development Certification"],
    toolsAndTechnologies: ["C/C++", "Keil uVision", "STM32CubeIDE", "Linux", "Oscilloscopes", "I2C/SPI/UART"],
    skills: [
      { skillName: "C++", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.3, priority: 1 },
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 2 },
      { skillName: "Data Structures", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 4 },
      { skillName: "Logical Reasoning", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.9, priority: 5 },
    ],
  },
  {
    title: "IoT Engineer",
    domain: "Internet of Things & Connected Systems",
    description: "Build connected edge devices, sensor data aggregation pipelines, MQTT telemetry, and cloud integration.",
    courses: ["B.Tech", "BE", "BCA", "MCA"],
    departments: ["Electronics & Communication Engineering", "Computer Science & Engineering", "Information Technology", "Computer Science"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Degree in ECE, CS, or IT",
    salaryRange: "₹6,00,000 - ₹15,00,000 / year",
    certifications: ["AWS Certified IoT - Specialty", "Cisco IoT Fundamentals"],
    toolsAndTechnologies: ["MQTT", "Raspberry Pi", "ESP32", "Python", "AWS IoT Core"],
    skills: [
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "C++", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.1, priority: 2 },
      { skillName: "AWS", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.9, priority: 4 },
    ],
  },
  {
    title: "Mechanical Design Engineer",
    domain: "Mechanical & Product Engineering",
    description: "Design 3D mechanical components, perform FEA simulation, optimize for manufacturing (DFM), and produce engineering drawings.",
    courses: ["B.Tech", "BE", "Diploma", "M.Tech"],
    departments: ["Mechanical Engineering", "Automobile Engineering", "Robotics & Automation", "Industrial & Production Engineering", "Mechanical"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/BE or Diploma in Mechanical/Automobile Engineering",
    salaryRange: "₹5,00,000 - ₹14,00,000 / year",
    certifications: ["Certified SolidWorks Professional (CSWP)", "Autodesk Certified Professional AutoCAD"],
    toolsAndTechnologies: ["SolidWorks", "AutoCAD", "ANSYS", "CATIA", "GD&T Standards"],
    skills: [
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.3, priority: 1 },
      { skillName: "Quantitative Aptitude", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Logical Reasoning", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.9, priority: 4 },
      { skillName: "Teamwork", category: SkillCategory.SOFT_SKILL, requiredLevel: 70, weight: 0.6, priority: 5 },
    ],
  },
  {
    title: "CAD Engineer",
    domain: "Computer Aided Design & Drafting",
    description: "Develop detailed 2D/3D component models, assembly tolerances, sheet metal designs, and BOMs.",
    courses: ["B.Tech", "BE", "Diploma"],
    departments: ["Mechanical Engineering", "Civil Engineering", "Automobile Engineering", "Mechanical", "Civil"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Degree or Diploma in Mechanical/Civil",
    salaryRange: "₹4,50,000 - ₹11,00,000 / year",
    certifications: ["Autodesk Certified Professional", "SolidWorks CSWA/CSWP"],
    toolsAndTechnologies: ["AutoCAD", "SolidWorks", "PTC Creo", "CATIA"],
    skills: [
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 1.2, priority: 1 },
      { skillName: "Quantitative Aptitude", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 1.1, priority: 2 },
      { skillName: "Logical Reasoning", category: SkillCategory.APTITUDE, requiredLevel: 70, weight: 0.9, priority: 3 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 70, weight: 0.6, priority: 4 },
    ],
  },
  {
    title: "Structural Engineer",
    domain: "Civil & Infrastructure Engineering",
    description: "Analyze and design load-bearing structural frameworks (RCC/Steel), foundation systems, and seismic safety compliance.",
    courses: ["B.Tech", "BE", "M.Tech"],
    departments: ["Civil Engineering", "Structural Engineering", "Environmental Engineering", "Civil"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/BE in Civil Engineering or M.Tech Structures",
    salaryRange: "₹5,50,000 - ₹15,00,000 / year",
    certifications: ["STAAD.Pro Certified Professional", "Bentley Structural Analysis Certificate"],
    toolsAndTechnologies: ["STAAD.Pro", "ETABS", "AutoCAD", "Revit Structure", "IS Codes (IS 456, IS 800)"],
    skills: [
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.3, priority: 1 },
      { skillName: "Quantitative Aptitude", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.2, priority: 2 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 70, weight: 0.7, priority: 4 },
    ],
  },
  {
    title: "Site Engineer",
    domain: "Construction & Site Operations",
    description: "Supervise civil site construction, quality control checks, material testing, safety protocols, and contractor workflows.",
    courses: ["B.Tech", "BE", "Diploma"],
    departments: ["Civil Engineering", "Construction Technology", "Civil"],
    isCrossDisciplinary: false,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech or Diploma in Civil Engineering",
    salaryRange: "₹4,00,000 - ₹10,00,000 / year",
    certifications: ["Construction Safety Certificate (OSHA)", "Quality Control Inspector Certificate"],
    toolsAndTechnologies: ["AutoCAD", "Total Station", "MS Project", "Excel"],
    skills: [
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 1.2, priority: 1 },
      { skillName: "Leadership", category: SkillCategory.SOFT_SKILL, requiredLevel: 75, weight: 1.1, priority: 2 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Teamwork", category: SkillCategory.SOFT_SKILL, requiredLevel: 80, weight: 0.9, priority: 4 },
    ],
  },

  // ═════════════════════════════════════════════════════════════════════════
  // 6. CROSS-DISCIPLINARY ROLES (Universal across multiple degrees)
  // ═════════════════════════════════════════════════════════════════════════
  {
    title: "Data Analyst",
    domain: "Business Intelligence & Data Analysis",
    description: "Transform complex operational datasets into executive dashboards, cohort analyses, and strategic growth metrics.",
    courses: ["B.Tech", "B.Com", "BBA", "BCA", "B.Sc"],
    departments: ["Computer Science & Engineering", "Information Technology", "Data Science & Analytics", "Accounting & Finance", "Business Analytics", "Computer Science"],
    isCrossDisciplinary: true,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Any analytical undergraduate degree (Engineering, Commerce, Science, Business)",
    salaryRange: "₹5,00,000 - ₹13,00,000 / year",
    certifications: ["Google Data Analytics Professional Certificate", "Microsoft Certified: Power BI Data Analyst"],
    toolsAndTechnologies: ["SQL", "Excel", "Power BI", "Tableau", "Python", "Google Sheets"],
    skills: [
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.3, priority: 1 },
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 2 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.1, priority: 3 },
      { skillName: "Quantitative Aptitude", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 1.0, priority: 4 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 75, weight: 0.8, priority: 5 },
    ],
  },
  {
    title: "Data Scientist",
    domain: "Data Science & Analytics",
    description: "Extract actionable predictive insights from multi-modal structured and unstructured datasets using statistical modeling.",
    courses: ["B.Tech", "BE", "B.Sc", "M.Sc", "MCA"],
    departments: ["Artificial Intelligence & Machine Learning", "Data Science & Analytics", "Computer Science & Engineering", "Computer Science", "Mathematics", "Statistics"],
    isCrossDisciplinary: true,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Degree in Engineering, Data Science, Statistics, or Math",
    salaryRange: "₹7,50,000 - ₹20,00,000 / year",
    certifications: ["IBM Data Science Professional Certificate", "Google Advanced Data Analytics Certificate"],
    toolsAndTechnologies: ["Python", "R", "SQL", "Pandas", "Scikit-Learn", "Tableau", "Jupyter"],
    skills: [
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 85, weight: 1.2, priority: 1 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 80, weight: 1.1, priority: 2 },
      { skillName: "Machine Learning", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 3 },
      { skillName: "Quantitative Aptitude", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 4 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.0, priority: 5 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 75, weight: 0.7, priority: 6 },
    ],
  },
  {
    title: "Business Analyst",
    domain: "Business Strategy & Process Engineering",
    description: "Bridge the gap between business stakeholders and technical teams through requirement gathering and process design.",
    courses: ["BBA", "MBA", "B.Tech", "B.Com", "BCA"],
    departments: ["Business Analytics", "Finance", "Marketing", "Computer Science & Engineering", "Computer Science", "Management"],
    isCrossDisciplinary: true,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Undergraduate degree in Business, Engineering, or Commerce",
    salaryRange: "₹6,50,000 - ₹16,00,000 / year",
    certifications: ["ECBA (Entry Certificate in Business Analysis)", "Agile Scrum Master (CSM)"],
    toolsAndTechnologies: ["Jira", "Confluence", "SQL", "Tableau", "Draw.io / Visio", "Excel"],
    skills: [
      { skillName: "Business Analytics", category: SkillCategory.DOMAIN, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.9, priority: 2 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.1, priority: 3 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.1, priority: 4 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 80, weight: 1.1, priority: 5 },
      { skillName: "Teamwork", category: SkillCategory.SOFT_SKILL, requiredLevel: 75, weight: 0.8, priority: 6 },
    ],
  },
  {
    title: "Product Manager",
    domain: "Product Strategy & Lifecycle",
    description: "Define product vision, prioritize roadmap backlogs, coordinate engineering sprints, and drive go-to-market execution.",
    courses: ["B.Tech", "BBA", "MBA", "BCA"],
    departments: ["Computer Science & Engineering", "Computer Science", "Business Analytics", "Information Technology", "Management"],
    isCrossDisciplinary: true,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "Degree in Engineering, Computer Science, or Business",
    salaryRange: "₹9,00,000 - ₹24,00,000 / year",
    certifications: ["Pragmatic Institute Certified", "Product School PMC", "Scrum Product Owner (CSPO)"],
    toolsAndTechnologies: ["Jira", "Figma", "Mixpanel", "SQL", "Notion", "Postman"],
    skills: [
      { skillName: "Business Analytics", category: SkillCategory.DOMAIN, requiredLevel: 80, weight: 1.2, priority: 1 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 85, weight: 1.2, priority: 2 },
      { skillName: "Communication", category: SkillCategory.SOFT_SKILL, requiredLevel: 85, weight: 1.2, priority: 3 },
      { skillName: "Leadership", category: SkillCategory.SOFT_SKILL, requiredLevel: 80, weight: 1.0, priority: 4 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 65, weight: 0.7, priority: 5 },
    ],
  },
  {
    title: "Cybersecurity Analyst",
    domain: "Security & Information Assurance",
    description: "Identify vulnerabilities, monitor threat vectors, implement security compliance, and protect corporate systems.",
    courses: ["B.Tech", "BE", "BCA", "MCA", "B.Sc"],
    departments: ["Computer Science & Engineering", "Information Technology", "Computer Science", "Cyber Security & Forensics"],
    isCrossDisciplinary: true,
    experienceLevel: "Entry Level (0-2 years)",
    educationRequirements: "B.Tech/BE in CS/IT/Cybersecurity or certifications",
    salaryRange: "₹6,50,000 - ₹17,00,000 / year",
    certifications: ["CompTIA Security+", "Certified Ethical Hacker (CEH)", "Cisco CCNA Security"],
    toolsAndTechnologies: ["Wireshark", "Nmap", "Metasploit", "Burp Suite", "Linux", "Splunk"],
    skills: [
      { skillName: "Python", category: SkillCategory.TECHNICAL, requiredLevel: 75, weight: 1.0, priority: 1 },
      { skillName: "SQL", category: SkillCategory.TECHNICAL, requiredLevel: 70, weight: 0.8, priority: 2 },
      { skillName: "Logical Reasoning", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.1, priority: 3 },
      { skillName: "Analytical Thinking", category: SkillCategory.APTITUDE, requiredLevel: 80, weight: 1.1, priority: 4 },
      { skillName: "Problem Solving", category: SkillCategory.APTITUDE, requiredLevel: 75, weight: 0.9, priority: 5 },
    ],
  },
];

export async function seedCareerRoles() {
  console.log(`💼 Seeding ${CAREER_ROLES_SEED.length} dynamic Career Roles & Industry Benchmarks...`);

  let seededCount = 0;
  for (const roleData of CAREER_ROLES_SEED) {
    const role = await prisma.careerRole.upsert({
      where: { title: roleData.title },
      update: {
        domain: roleData.domain,
        description: roleData.description,
        courses: roleData.courses as any,
        departments: roleData.departments as any,
        isCrossDisciplinary: roleData.isCrossDisciplinary,
        isActive: true,
        experienceLevel: roleData.experienceLevel,
        educationRequirements: roleData.educationRequirements,
        salaryRange: roleData.salaryRange,
        certifications: roleData.certifications as any,
        toolsAndTechnologies: roleData.toolsAndTechnologies as any,
      },
      create: {
        title: roleData.title,
        domain: roleData.domain,
        description: roleData.description,
        courses: roleData.courses as any,
        departments: roleData.departments as any,
        isCrossDisciplinary: roleData.isCrossDisciplinary,
        isActive: true,
        experienceLevel: roleData.experienceLevel,
        educationRequirements: roleData.educationRequirements,
        salaryRange: roleData.salaryRange,
        certifications: roleData.certifications as any,
        toolsAndTechnologies: roleData.toolsAndTechnologies as any,
      },
    });

    // Seed/upsert required skills for this role
    for (const req of roleData.skills) {
      let skill = await prisma.skill.findUnique({
        where: { name: req.skillName },
      });

      if (!skill) {
        skill = await prisma.skill.create({
          data: {
            name: req.skillName,
            category: req.category || SkillCategory.TECHNICAL,
            description: `${req.skillName} competency`,
          },
        });
      }

      await prisma.careerRoleSkill.upsert({
        where: {
          careerRoleId_skillId: {
            careerRoleId: role.id,
            skillId: skill.id,
          },
        },
        update: {
          requiredLevel: req.requiredLevel,
          weight: req.weight,
          priority: req.priority,
        },
        create: {
          careerRoleId: role.id,
          skillId: skill.id,
          requiredLevel: req.requiredLevel,
          weight: req.weight,
          priority: req.priority,
        },
      });
    }

    seededCount++;
  }

  console.log(`✅ Successfully seeded ${seededCount} career roles with full industry benchmarks!`);
}

if (require.main === module) {
  seedCareerRoles()
    .catch((e) => {
      console.error("Error seeding career roles:", e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
